services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=examplepass
    volumes:
      - db-data:/data/db
    expose:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=examplepass
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

volumes:
  db-data:
